DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS film;

CREATE TABLE film(
id SERIAL8 PRIMARY KEY,
title VARCHAR(255),
price INT4
)

CREATE TABLE customer(
id SERIAL8 PRIMARY KEY,
name VARCHAR(255),
funds INT4
)

CREATE TABLE tickets(
id SERIAL8 PRIMARY KEY,
film_id INT8 REFERENCES film(id),
customer_id REFERENCES customer(id)

)
